"""fix foreign keys

Revision ID: 638e1785d0a5
Revises: fdf6b76ef711
Create Date: 2024-01-20 18:09:13.616190

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '638e1785d0a5'
down_revision = 'fdf6b76ef711'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
