"""fix foreign keys

Revision ID: 7e97c42d2180
Revises: e0f178993f1d
Create Date: 2024-01-20 18:02:00.640166

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '7e97c42d2180'
down_revision = 'e0f178993f1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message_threads', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'message_threads', 'users', ['user_id'], ['id'])
    op.add_column('user_settings', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'user_settings', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_settings', type_='foreignkey')
    op.drop_column('user_settings', 'user_id')
    op.drop_constraint(None, 'message_threads', type_='foreignkey')
    op.drop_column('message_threads', 'user_id')
    # ### end Alembic commands ###
