"""rename col to voise_answer and change to bool

Revision ID: 9474d16b4a58
Revises: ded271fb3af3
Create Date: 2024-01-21 21:38:24.496573

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '9474d16b4a58'
down_revision = 'ded271fb3af3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('voice_answer', sa.Boolean(), nullable=False))
    op.drop_column('user_settings', 'response_format')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('response_format', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('user_settings', 'voice_answer')
    # ### end Alembic commands ###
