"""delete user_settings id col and make user_id primary key

Revision ID: ded271fb3af3
Revises: d4c5cef90dc8
Create Date: 2024-01-21 20:25:21.248480

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'ded271fb3af3'
down_revision = 'd4c5cef90dc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('current_runnable', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_index('ix_user_settings_id', table_name='user_settings')
    op.drop_column('user_settings', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.create_index('ix_user_settings_id', 'user_settings', ['id'], unique=False)
    op.drop_column('user_settings', 'current_runnable')
    # ### end Alembic commands ###
