"""add messagethreads

Revision ID: e0f178993f1d
Revises: 6627f6f80ac3
Create Date: 2024-01-20 17:44:44.659805

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'e0f178993f1d'
down_revision = '6627f6f80ac3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_threads',
    sa.Column('thread_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('thread_id')
    )
    op.add_column('user_settings', sa.Column('gpt_model', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('user_settings', sa.Column('current_message_thread', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'current_message_thread')
    op.drop_column('user_settings', 'gpt_model')
    op.drop_table('message_threads')
    # ### end Alembic commands ###
