"""fix foreign keys

Revision ID: fdf6b76ef711
Revises: 7e97c42d2180
Create Date: 2024-01-20 18:03:29.329610

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'fdf6b76ef711'
down_revision = '7e97c42d2180'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
